# Site settings
title: BME Egyetemi Doktorandusz KÃ©pviselet
email:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://edk.inf.mit.bme.hu/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# additions

collections:
  lectures:
    output: true
  guidelines:
    output: true

repo: https://github.com/bme-edk/bme-edk.github.io/tree/master/

future: true
